# .github/workflows/gitflow-auto-pr.yml
name: Auto PR GitFlow

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create next release branch
        if: github.ref_name == 'develop'
        id: release
        shell: bash
        run: |
            git fetch origin '+refs/heads/*:refs/remotes/origin/*' || true

            LAST=$(git branch -r \
            | grep 'origin/release/' \
            | sed 's|.*origin/release/||' \
            | sort -V \
            | tail -n 1)

            if [[ -z "$LAST" ]]; then
                NEXT="1.0.0"
            else
                IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST"
                NEXT="$((MAJOR + 1)).0.0"
            fi

            BRANCH="release/$NEXT"

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            git checkout -b "$BRANCH"
            git push origin "$BRANCH"

            echo "base=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Define target branch
        id: flow
        shell: bash
        run: |
          BRANCH="${GITHUB_REF_NAME}"

          if [[ "$BRANCH" =~ ^feature/ ]]; then
            echo "base=develop" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" == "develop" ]]; then
            echo "base=${{ steps.release.outputs.base }}" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" =~ ^release/ ]]; then
            echo "base=main" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" =~ ^hotfix/ ]]; then
            echo "base=main" >> "$GITHUB_OUTPUT"
          fi

      - name: Create pull request
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD: ${{ github.ref_name }}
          BASE: ${{ steps.flow.outputs.base }}
        shell: bash
        run: |
          if [[ -z "$BASE" ]]; then
            exit 0
          fi

          gh pr create \
            --head "$HEAD" \
            --base "$BASE" \
            --title "Merge $HEAD into $BASE" \
            --body "Automatic GitFlow pull request."